apiVersion: v1
kind: Service
metadata:
  name: rtdad-consumer
  labels:
    app: rtdad-consumer
spec:
  type: NodePort
  selector:
    app: rtdad-consumer
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: {{ .Values.consumer.nodePort }}
